---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <applicationName>-dpy
  namespace: <applicationNamespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <applicationName>
  template:
    metadata:
      namespace: <applicationNamespace>
      labels:
        app: <applicationName>
    spec:
      containers:
      - name: <applicationName>
        # https://dev.azure.com/eagleperu/Juntoz/_wiki/wikis/Juntoz.wiki/101/Kubernetes
        image: <mydockerregistry>/<applicationName>:latest
        ports:
        - containerPort: <applicationPort>
        resources:
          limits:
            cpu: "0.5"
            memory: "200Mi"
          requests:
            cpu: "0.3"
            memory: "100Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /tools/probe
        #     port: <applicationPort>
        #   initialDelaySeconds: 3
        env:
        - name: API_PORT
          value: "<applicationPort>"
        - name: LOG_LEVEL
          value: info
        - name: RUN_ENV
          value: stg
---
apiVersion: v1
kind: Service
metadata:
  name: <applicationName>-svc
  namespace: <applicationNamespace>
spec:
  selector:
    app: <applicationName>
  ports:
    - port: <applicationPort>
      targetPort: <applicationPort>
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  # ambassador is located in the default namespace
  name: <applicationName>-mp
spec:
  prefix: <path>
  rewrite: <rewrite>
  service: http://<applicationName>-svc.<applicationNamespace>:<applicationPort>
