---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <applicationName>-dpy
  namespace: <applicationNamespace>
spec:
  replicas: __kub-pod-instancecount__
  selector:
    matchLabels:
      app: <applicationName>
  template:
    metadata:
      namespace: <applicationNamespace>
      labels:
        app: <applicationName>
    spec:
      containers:
      - name: <applicationName>
        image: my-docker-registry/<applicationName>:__kub-pod-tag__ # TODO: Set correct docker registry
        ports:
        - containerPort: <applicationPort>
        resources:
          limits:
            # cpu: "0.3"
            memory: "200Mi"
          # requests:
          #   cpu: "0.1"
          #   memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /tools/probe
            port: <applicationPort>
          initialDelaySeconds: 3
        env:
        - name: API_PORT
          value: "<applicationPort>"
        - name: LOG_LEVEL
          value: info
        - name: RUN_ENV
          value: __envname__
---
apiVersion: v1
kind: Service
metadata:
  name: <applicationName>-svc
  namespace: <applicationNamespace>
spec:
  selector:
    app: <applicationName>
  ports:
    - port: <applicationPort>
      targetPort: <applicationPort>
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: <applicationName>-mp
spec:
  prefix: # TODO: set correct prefix and entity name e.g. /x/entity
  rewrite: # TODO: remove the prefix e.g. /entity
  service: http://<applicationName>-svc.<applicationNamespace>:<applicationPort>
